### ISSUE TITLE
Allow contraining movement to be vertical or horizontal

### ISSUE THREAD

**Issue by ianhi** [ianhi/mpl-draggable-line#4]
### Description
A valid use case should be constraining an endpoint to move only along a certain axis. Perhaps just horizontal or vertical, but with some effort could be made to be arbitrary.

related to: #2 

inspired by @ubitux here: https://twitter.com/insouris/status/1558863351710629893

**Comment by ubitux** [comment]
I think it makes sense to allow to follow a curve. Here is the kind of stuff I very often do in desmos, which I'd like to reproduce with matplotlib:

https://user-images.githubusercontent.com/34467/184556895-65bbc987-cc70-4c10-803a-15944ba7825c.mp4

As you can see, the coordinate of the point depends on the variable, which is a slider but the inverse connection from the graph is also detected.

**Comment by ianhi** [comment]
@ubitux I've closed this issue as the proposed functionallity in the top comment is now possible - but I've opened a new issue to track your suggestion.
